### ISSUE TITLE
Does it work :)

### ISSUE THREAD

**Issue by marksev1** [Blagus/PySonde#1]
Hello Blagus,

thanks for this project. Does it work? Do you have some video demo of it somewhere in action :)?

**Comment by Blagus** [comment]
Hi, I apologize for the late response.

It works - kind of. It can decode RS41 wav files recorded with Gqrx and SDR#. The development is stopped for now because Python is too slow in math. Decoder itself should be rewritten as a C module, or the entire app in something faster, my current plan is to do it in Qt when I'll have time.

**Comment by marksev1** [comment]
Awesome, so will it be opensource too?

**Comment by Blagus** [comment]
Of course, FOSS and cross-platform, which is very easy to do with Qt. There are enough paid Windows-only apps, and zero simple to use ones for Linux/Android.

However, I can't talk about any deadlines. It might be done before this summer, and it might won't be ready until next year. Too many things over my head, plus another project, not published yet, which is (I think) even more awesome.

**Comment by marksev1** [comment]
Great great, looking forward to everything :)
